# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 11:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import housing_estate.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('HouseNo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('StreetName', models.CharField(max_length=30)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasGypsum', models.BooleanField(default='False')),
                ('HasAluminiumWindows', models.BooleanField(default='False')),
                ('HasTiles', models.BooleanField(default='False')),
                ('Rented', models.BooleanField(default='False')),
                ('SelfContained', models.BooleanField(default='False')),
                ('VanishedRoom', models.BooleanField(default='False')),
                ('HasWater', models.BooleanField(default='False')),
                ('HasElectricity', models.BooleanField(default='False')),
                ('ApartmentName', models.CharField(max_length=15)),
                ('NoOfRooms', models.IntegerField()),
                ('ApartmentSize', models.FloatField()),
                ('ApartmentPaymentMode', models.CharField(choices=[('3Months', 'Three Months'), ('6Months', 'Six Months'), ('1Year', 'One Year')], max_length=10)),
                ('price', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=housing_estate.models.get_image_path)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Compound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompoundName', models.CharField(max_length=20)),
                ('NoOfUnits', models.IntegerField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=housing_estate.models.get_image_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostelName', models.CharField(max_length=30)),
                ('NumOfRooms', models.IntegerField(verbose_name='Number of Rooms')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=housing_estate.models.get_image_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Address')),
            ],
        ),
        migrations.CreateModel(
            name='HostelRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasGypsum', models.BooleanField(default='False')),
                ('HasAluminiumWindows', models.BooleanField(default='False')),
                ('HasTiles', models.BooleanField(default='False')),
                ('Rented', models.BooleanField(default='False')),
                ('SelfContained', models.BooleanField(default='False')),
                ('VanishedRoom', models.BooleanField(default='False')),
                ('HasWater', models.BooleanField(default='False')),
                ('HasElectricity', models.BooleanField(default='False')),
                ('RoomNumber', models.IntegerField(verbose_name='Room Number')),
                ('Price', models.FloatField()),
                ('RoomSize', models.FloatField()),
                ('RoomPaymentMode', models.CharField(choices=[('3Months', 'Three Months'), ('6Months', 'Six Months'), ('1Year', 'One Year')], max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=housing_estate.models.get_image_path)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Hostel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasGypsum', models.BooleanField(default='False')),
                ('HasAluminiumWindows', models.BooleanField(default='False')),
                ('HasTiles', models.BooleanField(default='False')),
                ('Rented', models.BooleanField(default='False')),
                ('SelfContained', models.BooleanField(default='False')),
                ('VanishedRoom', models.BooleanField(default='False')),
                ('HasWater', models.BooleanField(default='False')),
                ('HasElectricity', models.BooleanField(default='False')),
                ('HouseName', models.CharField(max_length=20)),
                ('NoOfRooms', models.IntegerField()),
                ('HouseSize', models.FloatField()),
                ('price', models.FloatField()),
                ('HousePaymentMode', models.CharField(choices=[('3Months', 'Three Months'), ('6Months', 'Six Months'), ('1Year', 'One Year')], max_length=10)),
                ('picture', models.ImageField(blank=True, null=True, upload_to=housing_estate.models.get_image_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Address')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('MiddleName', models.CharField(blank=True, max_length=50, null=True)),
                ('LastName', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='house',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Owner'),
        ),
        migrations.AddField(
            model_name='hostel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Owner'),
        ),
        migrations.AddField(
            model_name='compound',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Owner'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='compound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='housing_estate.Compound'),
        ),
    ]
