# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-22 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housing_estate', '0002_auto_20170330_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='available_rooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Available rooms'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='Roomavalaibility',
            field=models.BooleanField(default=False),
        ),
    ]
