"""
Django settings for real_estate project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'e@=*uwb+_e8nqz*fa6k2b6bkvq55e)o3)69xl-=a)r!5#wievt'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#this email will be used to send email incase one need to reset his/her email
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER ='pngimbwa6@gmail.com'
EMAIL_HOST_PASSWORD = 'cgpyfrxjzcsrjmju'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'housing_estate',
    'geoposition'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'real_estate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'real_estate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'research',
        'USER': 'peterngimbwa',
        'PASSWORD': 'cosmas',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

'''
# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'#'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


'''
Static_root is where the server will look for files
when we go live(is where static file will be collected by server)
'''
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR),'static_in_env','static_root')
#STATIC_DIRS=/Users/peterngimbwa/Documents/python/real_estate/static_in_env/static_root


#Staticfiles_dirs is where our files will be put inside our project

STATICFILES_DIRS = (
    
    #STATIC_DIRS=/Users/peterngimbwa/Documents/python/real_estate/src/static_in_pro/our_static
    os.path.join(BASE_DIR, "static_in_pro","our_static"),
   # '/var/www/static/',
)

'''
MEDIA files are related to (user) content.
This directory will mainly contain files uploaded to the website.
'''

DATE_INPUT_FORMATS = ('%d-%m-%Y')

MEDIA_URL='/media/'
#MEDIA_ROOT=os.path.join(BASE_DIR, "static_in_env","media_root") #use it for production
MEDIA_ROOT=os.path.join(BASE_DIR,"static_in_pro","media_root") #for development 

GEOPOSITION_GOOGLE_MAPS_API_KEY = 'AIzaSyB8F5_RZQ_HLc2ANOwk1jcmL49vRoKXDoM'

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')